apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sandbox
  labels:
    app: postgres
    type: database
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        type: database
        env: production
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sandbox
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 30700
  selector:
   app: postgres