apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 30042
