apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-rc
  labels:
    app: frontend
    type: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2          
