apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: dev
  labels:
    app: webapp
    type: webapp
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
        type: webapp
        env: dev
    spec:
      containers:
        - name: webapp
          image: tutum/hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: dev
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: webapp