apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    app: backend-app
    type: backend
    env: production
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-app
        type: backend
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
