apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
    env: production
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
